language: java
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=vztot_internet-shop

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "vztot-1"
    token:
      secure: ${{ secrets.SONAR_TRAVIS_TOKEN }}
