language: java
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=vztot_internet-shop

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "vztot-1"
    token:
      secure: "QC4fL55ahT84C2XfDDMagI1XVlB6aJcdTDRahUwqXed7NNwGZyVoqPwePUYbJfUna9eG18r5Pr3cN3Xq64lwSUD+1k7Z/ghAFlrm93ALXYITWDqQjUKtkfm4rNUOGZGAes/Y2o1WF0552hCzT/lKwwx0YEbk68G2dF0wEjg9bxnvReuN40p+PIH77aj1WyPFagUgLh4tKqFcm0f+3bD9TbyH5HOGs77WfVjhAlSViA/tKjETQwwItQGmvMs7B8EOsnQntvMOZYMY89MYokEdIvuHgI5teG3eF8VkWaM8A9QxhMl441r8Zv2fTYUWfZBey+oVOJZsOsBkPoMWyiqUgxP13fj5iqjkVH8AnOS78oaoZpNVrp8r1noYeqpX8hXg/g8HJQDfRml7GE6Cli/Qhz2nCndsNsQFdKaV6SNXgsFTdd6wHxmWlIA1C/mqLyDHDMfFJUlx6BzGn7ZxvKCh9pN9axAxw3zSM8n4mJvIoCDam0CbZkYirVbTVuePs3FKiOVdI/6v2xZRLu8F56hBZt1LaMaQeRAMG1TF/PEgcJoRo8uJcS/wBMh630i8HO1JxIa50nKzBOIkFe2uhOHUZSqsx6R4CJXxrQDGqLMMHh34iR3lT2JH3UuI8pRpPMezpx/BOi/+kaY9Ngkn7tQ86ixuThAuctYLr/8gENbHSk8="
